# Math Foundations for Data Science

### Assignment - I

In [1]:
# importing useful libraries to perform the required operations

import numpy as np
import pandas as pd
import scipy.linalg as la    #library for linear algebra computation
from sympy import *          #library for symbolic mathematics

### a. Read a matrix A from a csv file and a vector b from another csv file

In [2]:
A=pd.read_csv("C:\\Users\\vlakshmisravani\\Desktop\\A.csv")
b=pd.read_csv("C:\\Users\\vlakshmisravani\\Desktop\\b.csv")

print("Matrix A : ")
print(A)
print()
print("Vector b : ")
print(b)

Matrix A : 
   -1  2  -3
0   2 -3   4
1   1 -2  -3
2  -2  3   4

Vector b : 
   4
0 -5
1 -4
2  5


### b. Perform LU decomposition for square matrix

In [3]:
# Decomposing matrix A into Upper and Lower triangular matrix

P, L, U = la.lu(A)   # the function scipy.linalg.lu performs the PLU decomposition

print('The L matrix is:')
print(L)

print('\nThe U matrix is:')
print(U)

The L matrix is:
[[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [-1.  -0.   1. ]]

The U matrix is:
[[ 2.  -3.   4. ]
 [ 0.  -0.5 -5. ]
 [ 0.   0.   8. ]]


In [4]:
print(np.dot(P.T, A))
print()
print(np.dot(L, U))    # P is an identity matrix and PA = LU

a = P.dot((L.dot(U)))  #checking if A = PLU
print("\nA:", a)

[[ 2. -3.  4.]
 [ 1. -2. -3.]
 [-2.  3.  4.]]

[[ 2. -3.  4.]
 [ 1. -2. -3.]
 [-2.  3.  4.]]

A: [[ 2. -3.  4.]
 [ 1. -2. -3.]
 [-2.  3.  4.]]


### c. Solve the equation Ax=b and check whether there are 0,1 or infinitely many solutions

In [5]:
A=np.array(A)
b=np.array(b).T

rank_A=np.linalg.matrix_rank(A)

aug_A= np.concatenate((A,b)) 
rank_aug_A=np.linalg.matrix_rank(aug_A)

#  Checking whether there are 0,1 or infinitely many solutions

if (rank_A==rank_aug_A) and (rank_aug_A==np.shape(A)[0]):
    print("The system has a unique solution")
    
elif (rank_A==rank_aug_A) and (rank_aug_A<np.shape(A)[0]):
    print("The system has infinitely many solutions")
    
if(rank_A<rank_aug_A):
    print("The system has no solutions")

The system has a unique solution


In [6]:
A=np.array(A)
b=np.array(b).T

# Solving the equation Ax=b using NumPy's np.lingalg.solve 

x = np.linalg.solve(A,b)
print("X:",x)

X: [[2.]
 [3.]
 [0.]]


### d.  Do the diagonalization of a matrix

In [7]:
M = Matrix([[1, -3, 3], [3, -5, 3], [6, -6, 4]]) 
print("Matrix : {} ".format(M))
   
# Use sympy.diagonalize() method 
P, D = M.diagonalize()  
      
print("Diagonal of a matrix : {}".format(D))

Matrix : Matrix([[1, -3, 3], [3, -5, 3], [6, -6, 4]]) 
Diagonal of a matrix : Matrix([[-2, 0, 0], [0, -2, 0], [0, 0, 4]])


### e.  Give exponential, sine and sigmoid functions on A

In [8]:
def sigmoid(x):
    return(1/(1 + np.exp(-x)))
def exponenstial(x):
    return np.exp(x)
def sinfun(x):
    return np.sin(x)

sig=[sigmoid(i) for i in A]
expo=[exponenstial(i) for i in A]
sinf=[sinfun(i) for i in A]

print("Sigmoid function on A:")
print(np.array(sig))

print("\nExponential function on A:")
print(np.array(expo))

print("\nSine function on A:")
print(np.array(sinf))

Sigmoid function on A:
[[0.88079708 0.04742587 0.98201379]
 [0.73105858 0.11920292 0.04742587]
 [0.11920292 0.95257413 0.98201379]]

Exponential function on A:
[[7.38905610e+00 4.97870684e-02 5.45981500e+01]
 [2.71828183e+00 1.35335283e-01 4.97870684e-02]
 [1.35335283e-01 2.00855369e+01 5.45981500e+01]]

Sine function on A:
[[ 0.90929743 -0.14112001 -0.7568025 ]
 [ 0.84147098 -0.90929743 -0.14112001]
 [-0.90929743  0.14112001 -0.7568025 ]]


### f. Find all the eigenpairs of A

In [9]:
#calculate eigenvalues and their corresponding eigenvectors

u,V = la.eig(A)

print("Eigen Values are\n", u)
print("\nEigen Vactors are\n", V)

Eigen Values are
 [ 2.22249451+3.61088486j  2.22249451-3.61088486j -0.44498903+0.j        ]

Eigen Vactors are
 [[ 0.80754072+0.j          0.80754072-0.j          0.80130537+0.j        ]
 [-0.06448432-0.3019094j  -0.06448432+0.3019094j   0.59676372+0.j        ]
 [-0.0034449 +0.50255209j -0.0034449 -0.50255209j -0.04222292+0.j        ]]
